// Code generated by "stringer -type ExpressionErrType errors.go"; DO NOT EDIT.

package crontimes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[noneExpressionErr-0]
	_ = x[ErrSyntaxValueAfterLastRule-1]
	_ = x[ErrSyntaxUnexpectCharacter-2]
	_ = x[ErrSyntaxUnexpectLocation-3]
	_ = x[ErrStepMustNotBeZero-4]
	_ = x[ErrValueOutOfValidRange-5]
	_ = x[ErrLastNotSupportInMinuteRule-6]
	_ = x[ErrWeekdayNotSupportInMinuteRule-7]
	_ = x[ErrLastNotSupportInHourRule-8]
	_ = x[ErrWeekdayNotSupportInHourRule-9]
	_ = x[ErrLastDayOfMonthSyntax-10]
	_ = x[ErrLastNotSupportInMonthRule-11]
	_ = x[ErrWeekdayNotSupportInMonthRule-12]
	_ = x[ErrWeekdayNotSupportInDayOfWeekRule-13]
}

const _ExpressionErrType_name = "noneExpressionErrErrSyntaxValueAfterLastRuleErrSyntaxUnexpectCharacterErrSyntaxUnexpectLocationErrStepMustNotBeZeroErrValueOutOfValidRangeErrLastNotSupportInMinuteRuleErrWeekdayNotSupportInMinuteRuleErrLastNotSupportInHourRuleErrWeekdayNotSupportInHourRuleErrLastDayOfMonthSyntaxErrLastNotSupportInMonthRuleErrWeekdayNotSupportInMonthRuleErrWeekdayNotSupportInDayOfWeekRule"

var _ExpressionErrType_index = [...]uint16{0, 17, 44, 70, 95, 115, 138, 167, 199, 226, 256, 279, 307, 338, 373}

func (i ExpressionErrType) String() string {
	if i < 0 || i >= ExpressionErrType(len(_ExpressionErrType_index)-1) {
		return "ExpressionErrType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExpressionErrType_name[_ExpressionErrType_index[i]:_ExpressionErrType_index[i+1]]
}
